### PR TITLE
Create Objectives for the TF

### PR DESCRIPTION
**Pull request by a-fox**
Here is the task force objective statement that will be worked on during meeting on 16th March.

### CODE REVIEW

**Comment by andorsk** [comment]
My suggestions are here: https://github.com/trustoverip/tswg-trust-registry-tf/pull/88. Tried to make a PR off your branch to suggest against, but your repo blocked.

@darrellodonnell we should align on the doc before merging it. I suggest we revert until we align.

**Comment by andorsk** [comment]
@a-fox the objectives did change between versions. I'd think that for v2 we'd want to limit the scope to a specific objective, and possibly expand scope later to larger trust decisions as we move to v3, v4, etc. We are purposely constraining the scope for v2 IMO.

**Comment by darrellodonnell** [comment]
LOL - too late!

**Comment by andorsk** [comment]
Lol @darrellodonnell we can revert easily. Let's discuss over the call.

**Pull request merged**
